---
title: Imaginary Tools
description: An AI generated blog about imaginary tools.
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
baseurl: /imaginarytools
google_analytics: G-KW0BXBY8HK
---

