name: Create New Post

on:
  schedule:
      # * is a special character in YAML so you have to quote this string
      - cron:  '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      
      - name: create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'newPost'
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      
      - name: Install dependencies
        run: pip install -r .github/workflows/requirements.txt
      
      - name: execute python script
        env:
            OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        run: python scripts/generate_post.py

      - name: commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Adding new post'

      - uses: repo-sync/pull-request@v2
        name: Create Pull Request
        with:
          destination_branch: "main"
          pr_title: "Creating new post"
          pr_body: "👑 *An automated PR*"
          pr_draft: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
